[project]
name = "da-music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keras>=3.15.0",
    "matplotlib>=3.11.0",
    "msgspec>=0.21.1",
    "numpy>=2.5.0",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "tensorflow>=2.21.0",
]
